### ISSUE TITLE
Website doesn't seem to work in Firefox browser

### ISSUE THREAD

**Issue by Nytra** [ProbablePrime/office-hours#8]
When clicking on an office hours link (for example [this one](https://officehours.probableprime.co.uk/episodes/primetime-2022-03-22/)) it just shows an audio player without subtitles and without any buttons to click on.

![Screenshot 2023-08-22 at 06-42-37 PrimeTime-2022-03-22](https://github.com/ProbablePrime/office-hours/assets/14206961/30cdf7f4-6f3b-4ae5-a39c-041aa39c4c5a)

I tested the same link in Microsoft Edge and it works fine.

**Comment by Nytra** [comment]
Update: so it seems that the buttons and subtitles are there, they are just the same color as the background so cannot be seen.

**Comment by ExoTheWicker** [comment]
I have the same issue

**Comment by ProbablePrime** [comment]
![image](https://github.com/ProbablePrime/office-hours/assets/8791132/a98a96c9-2577-4602-bd50-2d3f13138ee7)


It works fine on my version of Firefox here,  are any of you using any different Operating systems or Browser versions?

**Comment by Nytra** [comment]
Yes the main page https://officehours.probableprime.co.uk/ works fine, but if you click on one of the episode links you will see the problem.

**Comment by ProbablePrime** [comment]
OH, i see my apologies, thank you!

**Comment by ProbablePrime** [comment]
Ok this is all fixed now, thank you!
