### ISSUE TITLE
Rename some episodes

### ISSUE THREAD

**Issue by Lexevolution** [ProbablePrime/office-hours#9]
Hello Prime,

Would you be able to rename some of the episodes that don't match the formatting of the majority?

More specifically these are the ones that aren't correct, and what they should be named to:
| Old Name | New Name | Reference
| --- | --- | --- |
| `Prime04-13` | `PrimeTime-2022-04-12` | [Discord Message](https://discord.com/channels/402159838827905024/850128578271641610/963574355185524788) correlates to audio @ 0:15
| `Prime22-04-05` | `PrimeTime-2022-04-05` | [Sounder Post](https://discord.com/channels/402159838827905024/850128578271641610/961119163663933450)
| `Prime29-03-22` | `PrimeTime-2022-03-29` | [Sounder Post](https://discord.com/channels/402159838827905024/850128578271641610/958582274067140659)

I cross-referenced the office hours channel to be 100% certain of what names these should be.

**Comment by ProbablePrime** [comment]
With that information i absolutely can, I can also re-transcribe them.

**Comment by ProbablePrime** [comment]
The manifests will be a little wonky, till i rename these. I'll get to it shortly.

**Comment by ProbablePrime** [comment]
These are now renamed, i'll kick off transcriptions for them

**Comment by ProbablePrime** [comment]
![image](https://github.com/ProbablePrime/office-hours/assets/8791132/4094808e-d6b6-4bb2-b40b-5feb311bcdbe)
WOO

**Comment by ProbablePrime** [comment]
Sorted!
